# Generated by Django 4.0.4 on 2022-05-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='SecondFactor',
            new_name='secondFactor',
        ),
        migrations.AddField(
            model_name='client',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='Seleccionar opcion', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='zone',
            field=models.CharField(choices=[('T', 'Terminal de ómnibus'), ('M', 'Municipalidad de La Plata'), ('C', 'Cementerio')], max_length=30),
        ),
    ]
