# Generated by Django 4.0.4 on 2022-05-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0004_forum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secondFactor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
