# Generated by Django 4.0.4 on 2022-05-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0002_rename_isactive_user_is_active_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secondFactor',
        ),
    ]
