# Generated by Django 4.0.4 on 2022-05-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0002_rename_secondfactor_client_secondfactor_client_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AplicatedVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doseNumber', models.IntegerField(blank=True, choices=[(1, 1), (2, 2)])),
                ('aplicationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Formulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.BooleanField()),
                ('admissionDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('dateOfBirth', models.DateField()),
                ('zone', models.CharField(choices=[('Terminal de ómnibus', 'Terminal de ómnibus'), ('Municipalidad de La Plata', 'Municipalidad de La Plata'), ('Cementerio', 'Cementerio')], max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('secondFactor', models.IntegerField()),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('timeSpan', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='vaccinator',
            name='password',
            field=models.CharField(default=1234, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVacunatorio.user'),
        ),
        migrations.AddField(
            model_name='turn',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVacunatorio.vaccine'),
        ),
        migrations.AddField(
            model_name='formulary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVacunatorio.user'),
        ),
        migrations.AddField(
            model_name='aplicatedvaccine',
            name='formulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVacunatorio.formulary'),
        ),
        migrations.AddField(
            model_name='aplicatedvaccine',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVacunatorio.vaccine'),
        ),
    ]
