# Generated by Django 4.0.4 on 2022-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0003_remove_user_secondfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secondFactor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
