# Generated by Django 4.0.4 on 2022-06-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0005_admin_is_active_admin_is_admin_admin_is_vaccinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
