# Generated by Django 4.0.4 on 2022-06-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0006_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
    ]
