# Generated by Django 4.0.4 on 2022-06-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0007_remove_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='dni',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
