# Generated by Django 4.0.4 on 2022-06-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0008_admin_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinator',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
