# Generated by Django 4.0.4 on 2022-06-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0009_alter_vaccinator_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='dni',
        ),
        migrations.AlterField(
            model_name='vaccinator',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
