# Generated by Django 4.0.4 on 2022-06-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0011_alter_vaccinator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulary',
            name='amarilla_ok',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='formulary',
            name='covid_1_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='formulary',
            name='covid_2_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='formulary',
            name='gripe_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.CharField(default=None, max_length=140, null=True),
        ),
        migrations.DeleteModel(
            name='AplicatedVaccine',
        ),
    ]
