# Generated by Django 4.0.4 on 2022-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0012_formulary_amarilla_ok_formulary_covid_1_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinator',
            name='zone',
            field=models.CharField(choices=[('Terminal de ómnibus', 'Terminal de ómnibus'), ('Municipalidad de La Plata', 'Municipalidad de La Plata'), ('Cementerio', 'Cementerio')], default='Cementerio', max_length=30),
        ),
    ]
