# Generated by Django 4.0.4 on 2022-06-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0015_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
