# Generated by Django 4.0.4 on 2022-06-27 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVacunatorio', '0018_alter_turn_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionVacunatorio.vaccine')),
            ],
        ),
    ]
